export const SPRITE_SHEET_ASSET_KEYS = {
  NPC_1_WALK: 'NPC_1_WALK',
  NPC_1_IDLE: 'NPC_1_IDLE',
  DOOR: 'DOOR',
  SPEAKER: 'SPEAKER',
  BUTTON: 'BUTTON',
  BELT_START: 'BELT_START',
  BELT_MID: 'BELT_MID',
  BELT_END: 'BELT_END',
  HAMMER: 'HAMMER',
  FENCE: 'FENCE',
} as const;

export const IMAGE_ASSET_KEYS = {
  LEVEL_1: 'LEVEL_1',
  LEVEL_2: 'LEVEL_2',
  LEVEL_3: 'LEVEL_3',
  LEVEL_4: 'LEVEL_4',
  LEVEL_5: 'LEVEL_5',
  LEVEL_6: 'LEVEL_6',
  LEVEL_7: 'LEVEL_7',
  LEVEL_8: 'LEVEL_8',
  COLLISION: 'COLLISION',
  DASH_CIRCLE: 'DASH_CIRCLE',
  BRIDGE_TILE: 'BRIDGE_TILE',
  BRIDGE_SUPPORT: 'BRIDGE_SUPPORT',
  BRIDGE_BASE: 'BRIDGE_BASE',
  ENERGY: 'ENERGY',
  NPC_MODAL: 'NPC_MODAL',
  MAIN_MODAL: 'MAIN_MODAL',
  PROFILE_HEAD: 'PROFILE_HEAD',
  INFO_PANEL: 'INFO_PANEL',
  BACKGROUND: 'BACKGROUND',
  FULLSCREEN_BUTTON: 'FULLSCREEN_BUTTON',
  OVERLAY: 'OVERLAY',
} as const;

export const TUTORIAL_IMAGE_ASSET_KEYS = {
  TUTORIAL_SPEAKER: 'TUTORIAL_SPEAKER',
  TUTORIAL_ENERGY: 'TUTORIAL_ENERGY',
};

export const TILED_LEVEL_JSON = {
  TILED_LEVEL_1: 'TILED_LEVEL_1',
  TILED_LEVEL_2: 'TILED_LEVEL_2',
  TILED_LEVEL_3: 'TILED_LEVEL_3',
  TILED_LEVEL_4: 'TILED_LEVEL_4',
  TILED_LEVEL_5: 'TILED_LEVEL_5',
  TILED_LEVEL_6: 'TILED_LEVEL_6',
  TILED_LEVEL_7: 'TILED_LEVEL_7',
  TILED_LEVEL_8: 'TILED_LEVEL_8',
} as const;

export const DATA_ASSET_KEYS = {
  ANIMATIONS: 'ANIMATIONS',
} as const;

export const ATLAS_ASSET_KEYS = {
  FLARES: 'FLARES',
};
